name: Deploy to Pages

on:
  push:
    branches: [main, quartz]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout content
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          path: vault
      
      - name: Checkout Quartz
        uses: actions/checkout@v5
        with:
          repository: jackyzha0/quartz
          path: quartz
          fetch-depth: 0
      
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      
      - name: Install Quartz dependencies
        run: |
          cd quartz
          npm ci
      
      - name: Copy content and config
        run: |
          rm -rf quartz/content
          cp -r vault/content quartz/content
          cp vault/quartz.config.ts quartz/quartz.config.ts
          cp vault/quartz.layout.ts quartz/quartz.layout.ts
      
      - name: Build Quartz
        run: |
          cd quartz
          npx quartz build
      
      - uses: actions/configure-pages@v5
      
      - uses: actions/upload-pages-artifact@v4
        with:
          path: quartz/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
